# Generated by Django 5.1.3 on 2024-11-29 14:12

import club.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название компьютерного клуба",
                        max_length=255,
                        verbose_name="название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание клуба",
                        verbose_name="описание клуба",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="Опишите цену", max_length=255, verbose_name="цена"
                    ),
                ),
                (
                    "number_of_computers",
                    models.PositiveSmallIntegerField(
                        help_text="Введите общее количество компьютеров",
                        verbose_name="общее количество компьютеров",
                    ),
                ),
            ],
            options={
                "verbose_name": "клуб",
                "verbose_name_plural": "клубы",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="имя пользователя"),
                ),
                ("password", models.CharField(max_length=255, verbose_name="пароль")),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес компьютерного клуба",
                        max_length=255,
                        verbose_name="адрес",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Введите номер телефона",
                        max_length=255,
                        validators=[club.validators.phone_number_validator],
                        verbose_name="номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите электронную почту",
                        max_length=254,
                        verbose_name="электронная почта",
                    ),
                ),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        related_query_name="contact",
                        to="club.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "контакты",
                "verbose_name_plural": "контакты",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Напишите свой отзыв", verbose_name="описание отзыва"
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        help_text="Оцените в пяти звездах (. для нецелых чисел)",
                        max_length=3,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="оценка",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="дата написания отзыва"
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        related_query_name="feedbacks",
                        to="club.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="uploads/", verbose_name="изображение"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        related_query_name="gallery_images",
                        to="club.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "допольнительное изображение",
                "verbose_name_plural": "дополнительные изображения",
            },
        ),
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="uploads/", verbose_name="изображение"),
                ),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_image",
                        related_query_name="main_image",
                        to="club.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "главное изображение",
                "verbose_name_plural": "главные изображения",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="дата")),
                ("hours", models.JSONField(verbose_name="забронированные часы")),
                (
                    "computer_order",
                    models.PositiveSmallIntegerField(verbose_name="номер компьютера"),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        related_query_name="bookings",
                        to="club.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        related_query_name="bookings",
                        to="club.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "бронирование",
                "verbose_name_plural": "бронировании",
            },
        ),
    ]
