# Generated by Django 5.1.3 on 2024-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Оцените в пяти звездах", verbose_name="оценка"
            ),
        ),
    ]
