# Generated by Django 5.1.3 on 2024-12-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_alter_feedback_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="name",
            field=models.CharField(default=None, max_length=255, verbose_name="Автор"),
            preserve_default=False,
        ),
    ]
