# Generated by Django 5.1.3 on 2024-12-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_feedback_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(verbose_name="дата"),
        ),
    ]
